name: Pull request

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Node.js environment      
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16
          cache: "yarn"
          registry-url: "https://npm.pkg.github.com"

      - name: Install dependecies
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn
          

