name: Pull request

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Yarn CLI
        uses: CultureHQ/actions-yarn@v1.0.1
          
      - name: Install dependecies
        run:
          yarn
